const Timetable = require("../models/Timetable");

/**
 * Real College Timetable Data extracted directly from official timetable document.
 * Institution: Madhuben and Bhanubhai Patel Institute of Technology (CVM University)
 * Program: INFORMATION TECHNOLOGY (UG), Semester: 7, Div: 7IT-1, Room: B-305
 * Academic Year: 2026-2027
 *
 * Times in 24-hour "HH:mm" format.
 */
const defaultTimetable = [
  // ─── MONDAY ───
  {
    day: "Monday",
    startTime: "10:55",
    endTime: "11:45",
    subjectCode: "202047801",
    subjectName: "Advanced Software Engineering",
    facultyName: "MR. JIMESH RANA",
    room: "B-305",
    semester: "7",
    division: "7IT-1",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 1,
  },
  {
    day: "Monday",
    startTime: "10:55",
    endTime: "11:45",
    subjectCode: "202047803",
    subjectName: "Big Data Analytics",
    facultyName: "MR. PIYUSH SUTHAR",
    room: "B-310",
    semester: "7",
    division: "7IT-1",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 2,
  },
  {
    day: "Monday",
    startTime: "10:55",
    endTime: "11:45",
    subjectCode: "202047808",
    subjectName: "Management of IT Infrastructure",
    facultyName: "MR. CHETAN VERMA",
    room: "D-213",
    semester: "7",
    division: "7IT-1",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 3,
  },
  {
    day: "Monday",
    startTime: "11:50",
    endTime: "12:40",
    subjectCode: "202046707",
    subjectName: "Data Science and Visualization",
    facultyName: "DR. PRIYANKA PANCHAL",
    room: "B-305",
    semester: "7",
    division: "7IT-1",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 4,
  },
  {
    day: "Monday",
    startTime: "13:25",
    endTime: "14:15",
    subjectCode: "202046712",
    subjectName: "Mobile Application Development",
    facultyName: "MR. NITIN PATEL",
    room: "B-305",
    semester: "7",
    division: "7IT-1",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 5,
  },
  {
    day: "Monday",
    startTime: "14:20",
    endTime: "15:10",
    subjectCode: "202046715",
    subjectName: "UI/UX Design",
    facultyName: "DR. PRITESH PANDEY",
    room: "B-305",
    semester: "7",
    division: "7IT-1",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 6,
  },
  {
    day: "Monday",
    startTime: "14:20",
    endTime: "15:10",
    subjectCode: "202047804",
    subjectName: "Deep Learning and Applications",
    facultyName: "MS. BHUMIKA S. PRAJAPATI",
    room: "B-310",
    semester: "7",
    division: "7IT-1",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 7,
  },
  {
    day: "Monday",
    startTime: "15:15",
    endTime: "17:00",
    subjectCode: "202047801",
    subjectName: "Advanced Software Engineering Lab",
    facultyName: "MR. JIMESH RANA",
    room: "B003-3 (1)",
    semester: "7",
    division: "7IT-1",
    batch: "1A28",
    lectureType: "Practical",
    isActive: true,
    order: 8,
  },
  {
    day: "Monday",
    startTime: "15:15",
    endTime: "17:00",
    subjectCode: "202047803",
    subjectName: "Big Data Analytics Lab",
    facultyName: "MR. PIYUSH SUTHAR",
    room: "B003-3 (2)",
    semester: "7",
    division: "7IT-1",
    batch: "1B28",
    lectureType: "Practical",
    isActive: true,
    order: 9,
  },

  // ─── TUESDAY ───
  {
    day: "Tuesday",
    startTime: "10:55",
    endTime: "11:45",
    subjectCode: "202046710",
    subjectName: "Introduction to Cloud Computing",
    facultyName: "MS. JAYSHRI PATEL",
    room: "B-305",
    semester: "7",
    division: "7IT-1",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 1,
  },
  {
    day: "Tuesday",
    startTime: "11:50",
    endTime: "12:40",
    subjectCode: "202046715",
    subjectName: "UI/UX Design",
    facultyName: "DR. PRITESH PANDEY",
    room: "B-305",
    semester: "7",
    division: "7IT-1",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 2,
  },
  {
    day: "Tuesday",
    startTime: "11:50",
    endTime: "12:40",
    subjectCode: "202047804",
    subjectName: "Deep Learning and Applications",
    facultyName: "MS. BHUMIKA S. PRAJAPATI",
    room: "B-310",
    semester: "7",
    division: "7IT-1",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 3,
  },
  {
    day: "Tuesday",
    startTime: "13:25",
    endTime: "14:15",
    subjectCode: "202047801",
    subjectName: "Advanced Software Engineering Lab",
    facultyName: "MR. JIMESH RANA",
    room: "B-305",
    semester: "7",
    division: "7IT-1",
    batch: "1A8",
    lectureType: "Practical",
    isActive: true,
    order: 4,
  },
  {
    day: "Tuesday",
    startTime: "13:25",
    endTime: "14:15",
    subjectCode: "202047803",
    subjectName: "Big Data Analytics Lab",
    facultyName: "MR. PIYUSH SUTHAR",
    room: "B-310",
    semester: "7",
    division: "7IT-1",
    batch: "1A8",
    lectureType: "Practical",
    isActive: true,
    order: 5,
  },
  {
    day: "Tuesday",
    startTime: "13:25",
    endTime: "14:15",
    subjectCode: "202047808",
    subjectName: "Management of IT Infrastructure Lab",
    facultyName: "MR. CHETAN VERMA",
    room: "D-213",
    semester: "7",
    division: "7IT-1",
    batch: "1A8",
    lectureType: "Practical",
    isActive: true,
    order: 6,
  },
  {
    day: "Tuesday",
    startTime: "14:20",
    endTime: "15:10",
    subjectCode: "202046712",
    subjectName: "Mobile Application Development",
    facultyName: "MR. NITIN PATEL",
    room: "B-305",
    semester: "7",
    division: "7IT-1",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 7,
  },
  {
    day: "Tuesday",
    startTime: "15:15",
    endTime: "17:00",
    subjectCode: "202047801",
    subjectName: "Advanced Software Engineering Lab",
    facultyName: "MR. JIMESH RANA",
    room: "B003-3 (1)",
    semester: "7",
    division: "7IT-1",
    batch: "1A18",
    lectureType: "Practical",
    isActive: true,
    order: 8,
  },
  {
    day: "Tuesday",
    startTime: "15:15",
    endTime: "17:00",
    subjectCode: "202047803",
    subjectName: "Big Data Analytics Lab",
    facultyName: "MR. PIYUSH SUTHAR",
    room: "B003-3 (2)",
    semester: "7",
    division: "7IT-1",
    batch: "1B18",
    lectureType: "Practical",
    isActive: true,
    order: 9,
  },
  {
    day: "Tuesday",
    startTime: "15:15",
    endTime: "17:00",
    subjectCode: "202047808",
    subjectName: "Management of IT Infrastructure Lab",
    facultyName: "MR. CHETAN VERMA",
    room: "B-109",
    semester: "7",
    division: "7IT-1",
    batch: "1C18",
    lectureType: "Practical",
    isActive: true,
    order: 10,
  },

  // ─── WEDNESDAY ───
  {
    day: "Wednesday",
    startTime: "10:55",
    endTime: "11:45",
    subjectCode: "202046707",
    subjectName: "Data Science and Visualization",
    facultyName: "DR. PRIYANKA PANCHAL",
    room: "B-305",
    semester: "7",
    division: "7IT-1",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 1,
  },
  {
    day: "Wednesday",
    startTime: "11:50",
    endTime: "12:40",
    subjectCode: "202046715",
    subjectName: "UI/UX Design",
    facultyName: "DR. PRITESH PANDEY",
    room: "B-305",
    semester: "7",
    division: "7IT-1",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 2,
  },
  {
    day: "Wednesday",
    startTime: "11:50",
    endTime: "12:40",
    subjectCode: "202047804",
    subjectName: "Deep Learning and Applications",
    facultyName: "MS. BHUMIKA S. PRAJAPATI",
    room: "B-310",
    semester: "7",
    division: "7IT-1",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 3,
  },
  {
    day: "Wednesday",
    startTime: "13:25",
    endTime: "15:10",
    subjectCode: "202046710",
    subjectName: "Introduction to Cloud Computing Lab",
    facultyName: "MR. HARSH GOSWAMI",
    room: "B003-1",
    semester: "7",
    division: "7IT-1",
    batch: "1A8",
    lectureType: "Practical",
    isActive: true,
    order: 4,
  },
  {
    day: "Wednesday",
    startTime: "13:25",
    endTime: "15:10",
    subjectCode: "202046712",
    subjectName: "Mobile Application Development Lab",
    facultyName: "MR. NITIN PATEL",
    room: "B-108",
    semester: "7",
    division: "7IT-1",
    batch: "1B8",
    lectureType: "Practical",
    isActive: true,
    order: 5,
  },
  {
    day: "Wednesday",
    startTime: "13:25",
    endTime: "15:10",
    subjectCode: "202046707",
    subjectName: "Data Science and Visualization Lab",
    facultyName: "DR. PRIYANKA PANCHAL",
    room: "A-105(1)",
    semester: "7",
    division: "7IT-1",
    batch: "1C8",
    lectureType: "Practical",
    isActive: true,
    order: 6,
  },
  {
    day: "Wednesday",
    startTime: "13:25",
    endTime: "15:10",
    subjectCode: "202046712",
    subjectName: "Mobile Application Development Lab",
    facultyName: "MS. PALAK DAVE",
    room: "A-105(2)",
    semester: "7",
    division: "7IT-1",
    batch: "1D8",
    lectureType: "Practical",
    isActive: true,
    order: 7,
  },
  {
    day: "Wednesday",
    startTime: "15:15",
    endTime: "17:00",
    subjectCode: "202047804",
    subjectName: "Deep Learning and Applications Lab",
    facultyName: "MS. BHUMIKA S. PRAJAPATI",
    room: "B003-3 (2)",
    semester: "7",
    division: "7IT-1",
    batch: "1D28",
    lectureType: "Practical",
    isActive: true,
    order: 8,
  },
  {
    day: "Wednesday",
    startTime: "15:15",
    endTime: "17:00",
    subjectCode: "202046715",
    subjectName: "UI/UX Design Lab",
    facultyName: "DR. PRITESH PANDEY",
    room: "B003-3 (1)",
    semester: "7",
    division: "7IT-1",
    batch: "1U28",
    lectureType: "Practical",
    isActive: true,
    order: 9,
  },

  // ─── THURSDAY ───
  {
    day: "Thursday",
    startTime: "10:55",
    endTime: "11:45",
    subjectCode: "202046710",
    subjectName: "Introduction to Cloud Computing",
    facultyName: "MS. JAYSHRI PATEL",
    room: "B-305",
    semester: "7",
    division: "7IT-1",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 1,
  },
  {
    day: "Thursday",
    startTime: "11:50",
    endTime: "12:40",
    subjectCode: "202046707",
    subjectName: "Data Science and Visualization",
    facultyName: "DR. PRIYANKA PANCHAL",
    room: "B-305",
    semester: "7",
    division: "7IT-1",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 2,
  },
  {
    day: "Thursday",
    startTime: "13:25",
    endTime: "15:10",
    subjectCode: "202046707",
    subjectName: "Data Science and Visualization Lab",
    facultyName: "DR. PRIYANKA PANCHAL",
    room: "A-105(1)",
    semester: "7",
    division: "7IT-1",
    batch: "1A8",
    lectureType: "Practical",
    isActive: true,
    order: 3,
  },
  {
    day: "Thursday",
    startTime: "13:25",
    endTime: "15:10",
    subjectCode: "202046707",
    subjectName: "Data Science and Visualization Lab",
    facultyName: "MS. RUCHI PATEL",
    room: "B003-1",
    semester: "7",
    division: "7IT-1",
    batch: "1B8",
    lectureType: "Practical",
    isActive: true,
    order: 4,
  },
  {
    day: "Thursday",
    startTime: "13:25",
    endTime: "15:10",
    subjectCode: "202046712",
    subjectName: "Mobile Application Development Lab",
    facultyName: "MR. NITIN PATEL",
    room: "B-109",
    semester: "7",
    division: "7IT-1",
    batch: "1C8",
    lectureType: "Practical",
    isActive: true,
    order: 5,
  },
  {
    day: "Thursday",
    startTime: "13:25",
    endTime: "15:10",
    subjectCode: "202046710",
    subjectName: "Introduction to Cloud Computing Lab",
    facultyName: "MR. HARSH GOSWAMI",
    room: "A-105(2)",
    semester: "7",
    division: "7IT-1",
    batch: "1D8",
    lectureType: "Practical",
    isActive: true,
    order: 6,
  },
  {
    day: "Thursday",
    startTime: "15:15",
    endTime: "17:00",
    subjectCode: "202047804",
    subjectName: "Deep Learning and Applications Lab",
    facultyName: "MS. BHUMIKA S. PRAJAPATI",
    room: "B003-3(2)",
    semester: "7",
    division: "7IT-1",
    batch: "1D18",
    lectureType: "Practical",
    isActive: true,
    order: 7,
  },
  {
    day: "Thursday",
    startTime: "15:15",
    endTime: "17:00",
    subjectCode: "202046715",
    subjectName: "UI/UX Design Lab",
    facultyName: "DR. PRITESH PANDEY",
    room: "B003-3(1)",
    semester: "7",
    division: "7IT-1",
    batch: "1U18",
    lectureType: "Practical",
    isActive: true,
    order: 8,
  },

  // ─── FRIDAY ───
  {
    day: "Friday",
    startTime: "09:05",
    endTime: "10:50",
    subjectCode: "202047804",
    subjectName: "Deep Learning and Applications Lab",
    facultyName: "MS. BHUMIKA S. PRAJAPATI",
    room: "B003-1",
    semester: "7",
    division: "7IT-1",
    batch: "1D8",
    lectureType: "Practical",
    isActive: true,
    order: 1,
  },
  {
    day: "Friday",
    startTime: "10:55",
    endTime: "11:45",
    subjectCode: "202046710",
    subjectName: "Introduction to Cloud Computing",
    facultyName: "MS. JAYSHRI PATEL",
    room: "B-305",
    semester: "7",
    division: "7IT-1",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 2,
  },
  {
    day: "Friday",
    startTime: "11:50",
    endTime: "12:40",
    subjectCode: "202047801",
    subjectName: "Advanced Software Engineering",
    facultyName: "MR. JIMESH RANA",
    room: "B-305",
    semester: "7",
    division: "7IT-1",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 3,
  },
  {
    day: "Friday",
    startTime: "11:50",
    endTime: "12:40",
    subjectCode: "202047803",
    subjectName: "Big Data Analytics",
    facultyName: "MR. PIYUSH SUTHAR",
    room: "B-310",
    semester: "7",
    division: "7IT-1",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 4,
  },
  {
    day: "Friday",
    startTime: "11:50",
    endTime: "12:40",
    subjectCode: "202047808",
    subjectName: "Management of IT Infrastructure",
    facultyName: "MR. CHETAN VERMA",
    room: "D-213",
    semester: "7",
    division: "7IT-1",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 5,
  },
  {
    day: "Friday",
    startTime: "14:20",
    endTime: "15:10",
    subjectCode: "202046712",
    subjectName: "Mobile Application Development",
    facultyName: "MR. NITIN PATEL",
    room: "B-305",
    semester: "7",
    division: "7IT-1",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 6,
  },
  {
    day: "Friday",
    startTime: "15:15",
    endTime: "17:00",
    subjectCode: "202046712",
    subjectName: "Mobile Application Development Lab",
    facultyName: "MR. NITIN PATEL",
    room: "B-109",
    semester: "7",
    division: "7IT-1",
    batch: "1A8",
    lectureType: "Practical",
    isActive: true,
    order: 7,
  },
  {
    day: "Friday",
    startTime: "15:15",
    endTime: "17:00",
    subjectCode: "202046710",
    subjectName: "Introduction to Cloud Computing Lab",
    facultyName: "MR. HARSH GOSWAMI",
    room: "B003-1",
    semester: "7",
    division: "7IT-1",
    batch: "1B8",
    lectureType: "Practical",
    isActive: true,
    order: 8,
  },
  {
    day: "Friday",
    startTime: "15:15",
    endTime: "17:00",
    subjectCode: "202046710",
    subjectName: "Introduction to Cloud Computing Lab",
    facultyName: "MS. JAYSHRI PATEL",
    room: "B003-3 (2)",
    semester: "7",
    division: "7IT-1",
    batch: "1C8",
    lectureType: "Practical",
    isActive: true,
    order: 9,
  },
  {
    day: "Friday",
    startTime: "15:15",
    endTime: "17:00",
    subjectCode: "202046707",
    subjectName: "Data Science and Visualization Lab",
    facultyName: "DR. PRIYANKA PANCHAL",
    room: "B003-3 (1)",
    semester: "7",
    division: "7IT-1",
    batch: "1D8",
    lectureType: "Practical",
    isActive: true,
    order: 10,
  },
];

const seedTimetable = async () => {
  try {
    // Force sync the timetable with exact college timetable entries
    await Timetable.deleteMany({});
    await Timetable.insertMany(defaultTimetable);
    console.log(`✅ Official College Timetable synced successfully (${defaultTimetable.length} entries).`);
  } catch (error) {
    console.error("❌ Error seeding official timetable:", error.message);
  }
};

module.exports = seedTimetable;
