const Timetable = require("../models/Timetable");

/**
 * Default timetable data for a college.
 * Based on a typical 6th Semester Computer Engineering timetable.
 * Times are in 24-hour "HH:mm" format.
 *
 * Lecture periods: 50 minutes each
 * Schedule:
 *   Period 1: 09:15 - 10:05
 *   Period 2: 10:05 - 10:55
 *   Period 3: 10:55 - 11:45
 *   Recess:   11:45 - 12:25
 *   Period 4: 12:25 - 13:15
 *   Period 5: 13:15 - 14:05
 *   Period 6: 14:05 - 14:55
 *   Period 7: 14:55 - 15:45
 */
const defaultTimetable = [
  // ─── MONDAY ───
  {
    day: "Monday",
    startTime: "09:15",
    endTime: "10:05",
    subjectCode: "CSC601",
    subjectName: "Mobile Application Development",
    facultyName: "Prof. A. Sharma",
    room: "Room 201",
    semester: "6",
    division: "A",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 1,
  },
  {
    day: "Monday",
    startTime: "10:05",
    endTime: "10:55",
    subjectCode: "CSC602",
    subjectName: "Machine Learning",
    facultyName: "Prof. B. Patel",
    room: "Room 201",
    semester: "6",
    division: "A",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 2,
  },
  {
    day: "Monday",
    startTime: "10:55",
    endTime: "11:45",
    subjectCode: "CSC603",
    subjectName: "Cloud Computing",
    facultyName: "Prof. C. Mehta",
    room: "Room 201",
    semester: "6",
    division: "A",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 3,
  },
  {
    day: "Monday",
    startTime: "12:25",
    endTime: "13:15",
    subjectCode: "CSC604",
    subjectName: "Information Security",
    facultyName: "Prof. D. Joshi",
    room: "Room 201",
    semester: "6",
    division: "A",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 4,
  },
  {
    day: "Monday",
    startTime: "13:15",
    endTime: "14:55",
    subjectCode: "CSL601",
    subjectName: "Machine Learning Lab",
    facultyName: "Prof. B. Patel",
    room: "Lab 301",
    semester: "6",
    division: "A",
    batch: "B1",
    lectureType: "Practical",
    isActive: true,
    order: 5,
  },

  // ─── TUESDAY ───
  {
    day: "Tuesday",
    startTime: "09:15",
    endTime: "10:05",
    subjectCode: "CSC603",
    subjectName: "Cloud Computing",
    facultyName: "Prof. C. Mehta",
    room: "Room 202",
    semester: "6",
    division: "A",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 1,
  },
  {
    day: "Tuesday",
    startTime: "10:05",
    endTime: "10:55",
    subjectCode: "CSC601",
    subjectName: "Mobile Application Development",
    facultyName: "Prof. A. Sharma",
    room: "Room 202",
    semester: "6",
    division: "A",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 2,
  },
  {
    day: "Tuesday",
    startTime: "10:55",
    endTime: "11:45",
    subjectCode: "CSC605",
    subjectName: "Big Data Analytics",
    facultyName: "Prof. E. Kaur",
    room: "Room 202",
    semester: "6",
    division: "A",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 3,
  },
  {
    day: "Tuesday",
    startTime: "12:25",
    endTime: "14:05",
    subjectCode: "CSL602",
    subjectName: "Mobile Application Development Lab",
    facultyName: "Prof. A. Sharma",
    room: "Lab 302",
    semester: "6",
    division: "A",
    batch: "B2",
    lectureType: "Practical",
    isActive: true,
    order: 4,
  },
  {
    day: "Tuesday",
    startTime: "14:05",
    endTime: "14:55",
    subjectCode: "CSC602",
    subjectName: "Machine Learning",
    facultyName: "Prof. B. Patel",
    room: "Room 202",
    semester: "6",
    division: "A",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 5,
  },

  // ─── WEDNESDAY ───
  {
    day: "Wednesday",
    startTime: "09:15",
    endTime: "10:05",
    subjectCode: "CSC604",
    subjectName: "Information Security",
    facultyName: "Prof. D. Joshi",
    room: "Room 203",
    semester: "6",
    division: "A",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 1,
  },
  {
    day: "Wednesday",
    startTime: "10:05",
    endTime: "10:55",
    subjectCode: "CSC605",
    subjectName: "Big Data Analytics",
    facultyName: "Prof. E. Kaur",
    room: "Room 203",
    semester: "6",
    division: "A",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 2,
  },
  {
    day: "Wednesday",
    startTime: "10:55",
    endTime: "11:45",
    subjectCode: "CSC601",
    subjectName: "Mobile Application Development",
    facultyName: "Prof. A. Sharma",
    room: "Room 203",
    semester: "6",
    division: "A",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 3,
  },
  {
    day: "Wednesday",
    startTime: "12:25",
    endTime: "14:05",
    subjectCode: "CSL603",
    subjectName: "Cloud Computing Lab",
    facultyName: "Prof. C. Mehta",
    room: "Lab 303",
    semester: "6",
    division: "A",
    batch: "B1",
    lectureType: "Practical",
    isActive: true,
    order: 4,
  },
  {
    day: "Wednesday",
    startTime: "14:05",
    endTime: "14:55",
    subjectCode: "CSC603",
    subjectName: "Cloud Computing",
    facultyName: "Prof. C. Mehta",
    room: "Room 203",
    semester: "6",
    division: "A",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 5,
  },

  // ─── THURSDAY ───
  {
    day: "Thursday",
    startTime: "09:15",
    endTime: "10:05",
    subjectCode: "CSC602",
    subjectName: "Machine Learning",
    facultyName: "Prof. B. Patel",
    room: "Room 204",
    semester: "6",
    division: "A",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 1,
  },
  {
    day: "Thursday",
    startTime: "10:05",
    endTime: "10:55",
    subjectCode: "CSC604",
    subjectName: "Information Security",
    facultyName: "Prof. D. Joshi",
    room: "Room 204",
    semester: "6",
    division: "A",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 2,
  },
  {
    day: "Thursday",
    startTime: "10:55",
    endTime: "11:45",
    subjectCode: "CSC602",
    subjectName: "Machine Learning",
    facultyName: "Prof. B. Patel",
    room: "Room 204",
    semester: "6",
    division: "A",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 3,
  },
  {
    day: "Thursday",
    startTime: "12:25",
    endTime: "14:05",
    subjectCode: "CSL604",
    subjectName: "Information Security Lab",
    facultyName: "Prof. D. Joshi",
    room: "Lab 301",
    semester: "6",
    division: "A",
    batch: "B2",
    lectureType: "Practical",
    isActive: true,
    order: 4,
  },
  {
    day: "Thursday",
    startTime: "14:05",
    endTime: "14:55",
    subjectCode: "CSC605",
    subjectName: "Big Data Analytics",
    facultyName: "Prof. E. Kaur",
    room: "Room 204",
    semester: "6",
    division: "A",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 5,
  },

  // ─── FRIDAY ───
  {
    day: "Friday",
    startTime: "09:15",
    endTime: "10:05",
    subjectCode: "CSC605",
    subjectName: "Big Data Analytics",
    facultyName: "Prof. E. Kaur",
    room: "Room 205",
    semester: "6",
    division: "A",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 1,
  },
  {
    day: "Friday",
    startTime: "10:05",
    endTime: "10:55",
    subjectCode: "CSC603",
    subjectName: "Cloud Computing",
    facultyName: "Prof. C. Mehta",
    room: "Room 205",
    semester: "6",
    division: "A",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 2,
  },
  {
    day: "Friday",
    startTime: "10:55",
    endTime: "11:45",
    subjectCode: "CSC604",
    subjectName: "Information Security",
    facultyName: "Prof. D. Joshi",
    room: "Room 205",
    semester: "6",
    division: "A",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 3,
  },
  {
    day: "Friday",
    startTime: "12:25",
    endTime: "14:05",
    subjectCode: "CSL605",
    subjectName: "Big Data Analytics Lab",
    facultyName: "Prof. E. Kaur",
    room: "Lab 302",
    semester: "6",
    division: "A",
    batch: "B1",
    lectureType: "Practical",
    isActive: true,
    order: 4,
  },
  {
    day: "Friday",
    startTime: "14:05",
    endTime: "14:55",
    subjectCode: "CSC601",
    subjectName: "Mobile Application Development",
    facultyName: "Prof. A. Sharma",
    room: "Room 205",
    semester: "6",
    division: "A",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 5,
  },

  // ─── SATURDAY ───
  {
    day: "Saturday",
    startTime: "09:15",
    endTime: "10:05",
    subjectCode: "CSC601",
    subjectName: "Mobile Application Development",
    facultyName: "Prof. A. Sharma",
    room: "Room 201",
    semester: "6",
    division: "A",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 1,
  },
  {
    day: "Saturday",
    startTime: "10:05",
    endTime: "10:55",
    subjectCode: "CSC602",
    subjectName: "Machine Learning",
    facultyName: "Prof. B. Patel",
    room: "Room 201",
    semester: "6",
    division: "A",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 2,
  },
  {
    day: "Saturday",
    startTime: "10:55",
    endTime: "11:45",
    subjectCode: "CSC605",
    subjectName: "Big Data Analytics",
    facultyName: "Prof. E. Kaur",
    room: "Room 201",
    semester: "6",
    division: "A",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 3,
  },
  {
    day: "Saturday",
    startTime: "12:25",
    endTime: "13:15",
    subjectCode: "CSC603",
    subjectName: "Cloud Computing",
    facultyName: "Prof. C. Mehta",
    room: "Room 201",
    semester: "6",
    division: "A",
    batch: "",
    lectureType: "Lecture",
    isActive: true,
    order: 4,
  },
];

const seedTimetable = async () => {
  try {
    const count = await Timetable.countDocuments();
    if (count === 0) {
      await Timetable.insertMany(defaultTimetable);
      console.log(`✅ Timetable seeded with ${defaultTimetable.length} lecture entries.`);
      console.log("   NOTE: Update faculty IDs in the Timetable collection using Admin > Manage Timetable");
      console.log("         to link actual registered faculty members for face verification authorization.");
    }
  } catch (error) {
    console.error("❌ Error seeding timetable:", error.message);
  }
};

module.exports = seedTimetable;
